# Generated by Django 3.0.7 on 2020-07-07 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_web_app', '0002_auto_20200704_1538'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associate_id', models.CharField(max_length=9, unique=True, verbose_name='Associate ID')),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
                ('rehire_date', models.DateField(blank=True, null=True, verbose_name='Rehire Date')),
                ('separation_date', models.DateField(blank=True, null=True, verbose_name='Separation Date')),
                ('job_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title')),
                ('flsa', models.CharField(choices=[('e', 'Exempt'), ('n', 'Non-Exempt')], max_length=1, verbose_name='FLSA Status')),
                ('pay_type', models.CharField(choices=[('s', 'Salaried'), ('h', 'Hourly')], max_length=1, verbose_name='Pay Type')),
                ('worker_category', models.CharField(choices=[('f', 'Full-Time'), ('p', 'Part-Time'), ('t', 'Temporary'), ('i', 'Intern')], max_length=1, verbose_name='Worker Category')),
                ('time_off_available', models.CharField(choices=[(True, 'Yes'), (False, 'No')], max_length=1, verbose_name='Is Time Off Available?')),
                ('homedepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_web_app.HomeDepartment')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
