# Generated by Django 3.0.7 on 2020-07-23 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_web_app', '0002_auto_20200704_1538'),
        ('separation_letter', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('t', 'Terminated')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='associate_id',
            field=models.CharField(max_length=9, null=True, unique=True, verbose_name='Associate ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='flsa',
            field=models.CharField(choices=[('e', 'Exempt'), ('n', 'Non-Exempt')], max_length=1, null=True, verbose_name='FLSA Status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hire_date',
            field=models.DateField(null=True, verbose_name='Hire Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='homedepartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_web_app.HomeDepartment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pay_type',
            field=models.CharField(choices=[('s', 'Salaried'), ('h', 'Hourly')], max_length=1, null=True, verbose_name='Pay Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='time_off_available',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='Is Time Off Available?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='worker_category',
            field=models.CharField(choices=[('f', 'Full-Time'), ('p', 'Part-Time'), ('t', 'Temporary'), ('i', 'Intern')], max_length=1, null=True, verbose_name='Worker Category'),
        ),
        migrations.CreateModel(
            name='EmployeeInfoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homedepartment', models.CharField(max_length=50, verbose_name='Home Department')),
                ('reports_to', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title')),
                ('flsa', models.CharField(max_length=15)),
                ('pay_type', models.CharField(max_length=15)),
                ('worker_category', models.CharField(max_length=20)),
                ('time_off_available', models.CharField(max_length=3)),
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='separation_letter.Letters')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
