# Generated by Django 3.0.7 on 2020-07-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200723_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='homedepartment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reports_to',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmployeeInfoHistory',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
