# Generated by Django 3.0.7 on 2020-07-27 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_web_app', '0003_employeeinfohistory_teammember'),
        ('separation_letter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letters',
            name='user',
        ),
        migrations.AddField(
            model_name='letters',
            name='team_member',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='letter_for', to='hr_web_app.EmployeeInfoHistory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='letters',
            name='letter_is_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_is_from', to='hr_web_app.TeamMember'),
        ),
    ]
