# Generated by Django 3.0.7 on 2020-07-27 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_web_app', '0002_auto_20200704_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('work_email', models.EmailField(max_length=254)),
                ('home_department', models.CharField(max_length=50, verbose_name='Home Department')),
                ('reports_to', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title')),
                ('flsa', models.CharField(max_length=15)),
                ('pay_type', models.CharField(max_length=15)),
                ('worker_category', models.CharField(max_length=20)),
                ('time_off_available', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('work_email', models.EmailField(max_length=254)),
                ('associate_id', models.CharField(max_length=9, unique=True, verbose_name='Associate ID')),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
                ('rehire_date', models.DateField(blank=True, null=True, verbose_name='Rehire Date')),
                ('separation_date', models.DateField(blank=True, null=True, verbose_name='Separation Date')),
                ('job_title', models.CharField(max_length=50, verbose_name='Job Title')),
                ('flsa', models.CharField(choices=[('e', 'Exempt'), ('n', 'Non-Exempt')], max_length=1, verbose_name='FLSA Status')),
                ('pay_type', models.CharField(choices=[('s', 'Salaried'), ('h', 'Hourly')], max_length=1, verbose_name='Pay Type')),
                ('worker_category', models.CharField(choices=[('f', 'Full-Time'), ('p', 'Part-Time'), ('t', 'Temporary'), ('i', 'Intern')], max_length=1, verbose_name='Worker Category')),
                ('time_off_available', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Is Time Off Available?')),
                ('status', models.CharField(choices=[('a', 'Active'), ('t', 'Terminated')], default='a', max_length=1)),
                ('homedepartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hr_web_app.HomeDepartment')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr_web_app.TeamMember')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
